### ISSUE TITLE
Crash on barcode Reading

### ISSUE THREAD

**Issue by rufutecharasu** [cslrfid/CS108-iOS-ObjC-App#19]
When using sample application to scan barcode, getting following crash. Unable to fetch barcode value, so the crash is occurring. Please fix it.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CSLBleTag barcodeValue]: unrecognized selector sent to instance 0x281585f00'
*** First throw call stack:
(0x192e7127c 0x19204b9f8 0x192d8dab8 0x192e76ac4 0x192e7875c 0x10303c55c 0x192d7a318 0x10303bf3c 0x1938f76a4 0x192a902c0 0x192a90220 0x192a93cdc)
libc++abi.dylib: terminating with uncaught exception of type NSException

` NSString* str1=((CSLReaderBarcode*)obj1).barcodeValue;`

**Comment by ksclam** [comment]
The tag/barcode data being captured are stored in the array filteredBuffer, where this mutable array is being optimized so that all objects are sorted on the list at the time being inserted.  The problem is that it is designed to hold barcode (CSLReaderBarcode object) or RIFD tag (CSLBleTag object) but not both at the same time.  As a quick fix, please do a [[CSLRfidAppEngine sharedAppEngine].reader.filteredBuffer removeAllObjects]; when switching between RFID and barcode reading.  

For a permanent fix, the branch hotfix-2.5 will be created for accommodating both RFID and barcode data on the filtered list.

**Comment by rufutecharasu** [comment]
Thanks. The above solution works for me.

**Comment by rufutecharasu** [comment]
I'm getting a different crash now. It i have doing inventory for more than one minute it gives a exception(out of bounds). Please find it in attached screenshot.

![outofbounds](https://user-images.githubusercontent.com/51223664/62859955-5c7de800-bd1c-11e9-8a33-d8ae35809e50.png)

**Comment by ksclam** [comment]
Are you trying to perform multiple bank inventory?  If so, kindly let me know you current configurations (e.g. read 1/2 additional bank and which bank).
